### ISSUE TITLE
octodns-dump crashes on Directional Pool record type

### ISSUE THREAD

**Issue by squintfox** [octodns/octodns-ultra#39]
We have a Directional Pool record in one of our UltraDNS zones and when trying to dump, it crashes:
```
  File "C:\x\venv\lib\site-packages\octodns\manager.py", line 884, in dump
    source.populate(zone, lenient=lenient)
  File "C:\x\venv\lib\site-packages\octodns_ultra\__init__.py", line 344, in populate
    record = self._record_for(
  File "C:\x\venv\lib\site-packages\octodns_ultra\__init__.py", line 308, in _record_for
    data = data_for(_type, records)
  File "C:\x\venv\lib\site-packages\octodns_ultra\__init__.py", line 202, in _data_for_multiple
    'ttl': records['ttl'],
KeyError: 'ttl'
```

This is the (obfuscated) JSON that is returned.

```
{
    "ownerName": "globalrecord.acme.com.",
    "profile": {
        "@context": "http://schemas.ultradns.com/DirPool.jsonschema",
        "description": "globalrecord.acme.com",
        "ignoreECS": false,
        "rdataInfo": [
            {
                "allNonConfigured": true,
                "ttl": 600,
                "type": "A"
            },
            {
                "geoInfo": {
                    "codes": [
                        "CA"
                    ],
                    "name": "xxx"
                },
                "ttl": 86400,
                "type": "SF"
            },
            {
                "geoInfo": {
                    "codes": [
                        "ASI",
                        "OCN"
                    ],
                    "name": "yyy"
                },
                "ttl": 86400,
                "type": "SF"
            },
            {
                "geoInfo": {
                    "codes": [
                        "AFR",
                        "EUR"
                    ],
                    "name": "zzz"
                },
                "ttl": 86400,
                "type": "SF"
            },
            {
                "geoInfo": {
                    "codes": [
                        "GB"
                    ],
                    "name": "xyz"
                },
                "ttl": 86400,
                "type": "SF"
            },
            {
                "geoInfo": {
                    "codes": [
                        "NAM"
                    ],
                    "name": "zyx"
                },
                "ttl": 86400,
                "type": "SF"
            }
        ]
    },
    "rdata": [
        "127.0.0.1",
        "xxxrecord.acme.com.",
        "yyyrecord.acme.com.",
        "zzzrecord.acme.com.",
        "xyzrecord.acme.com.",
        "zyxrecord.acme.com."
    ],
    "rrtype": "A (1)"
}
```

The docs are on page 110 here: https://ultra-portalstatic.ultradns.com/static/docs/REST-API_User_Guide.pdf.  I'm trying to understand the code better and maybe submit a PR, but I'm pretty new to octodns.  Ideally I'd like for it to be supported, but if not, it should skip over it and warn so it doesn't crash.

**Comment by ross** [comment]
> File "C:\x\venv\lib\site-packages\octodns_ultra\__init__.py", line 202, in _data_for_multiple

Line numbers are slightly different so some minor changes in the repo since the version you're hitting this on:

https://github.com/octodns/octodns-ultra/blob/619dbe80c1d282664babcc6d8b45056173c75035/octodns_ultra/__init__.py#L204-L209

Big picture Ultra's directional records not supported by octoDNS, 

https://github.com/octodns/octodns-ultra/blob/619dbe80c1d282664babcc6d8b45056173c75035/octodns_ultra/__init__.py#L77-L78

It should ignore them (and warn) w/o blowing up though. That probably means adding an extra if continue w/a logging warn about the skip around this point:

https://github.com/octodns/octodns-ultra/blob/619dbe80c1d282664babcc6d8b45056173c75035/octodns_ultra/__init__.py#L326-L327

Not really familiar with ultradns myself, but looking at the JSON you provided, thanks it's very helpful, I'm guessing that the best way to determine if it's a record that needs to be skipped may be to look at the 

        "@context": "http://schemas.ultradns.com/DirPool.jsonschema",

That schema seems like it's XML translated to JSON or something, but 🤷. 

Anyway, happy to 👁️ a PR and help get it over the line, but without having access to ultra I can't really do much directly.

**Comment by squintfox** [comment]
Sorry about the line numbers, I was tinkering trying to get it not to crash.  I think I understand what you're saying here.  I can do up a PR.
